name: CatData Pipeline Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openai pytest flake8
      - name: Run data ingestion
        run: python catdata-pipeline/data_ingest/data_ingest.py
      - name: Run rating computation
        run: python catdata-pipeline/rating/rating.py
      - name: Run content generation
        run: python catdata-pipeline/content_gen/content_gen.py
      - name: Update affiliate links
        run: python catdata-pipeline/utils/affiliates.py
      - name: Publish content
        run: python catdata-pipeline/cms_publish/cms_publish.py
      - name: Update analytics
        run: python catdata-pipeline/analytics_monitor/analytics_monitor.py
      - name: Lint with flake8
        run: flake8 catdata-pipeline
      - name: Run tests
        run: pytest catdata-pipeline
      - name: Slack notification on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"CatData pipeline job failed"}' "$SLACK_WEBHOOK_URL"
